FROM node:20-bookworm-slim
WORKDIR /app

COPY package.json package.json
COPY packages/indexer/package.json packages/indexer/package.json
RUN npm install --workspace=packages/indexer

COPY tsconfig.json tsconfig.json
COPY packages/indexer packages/indexer

RUN npm run build --workspace=packages/indexer

CMD ["node", "packages/indexer/dist/index.js"]
